### ISSUE TITLE
doc: merged files for 1.4 but need editing

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#4025]
These files were merged for the 1.4 release but still need editing:

- [x] PR #4001 tutorials/acrn_configuration_tool.rst
- [x] PR #3938 tutorials/enable_laag_secure_boot.rst
- [x] PR #3883 tutorials/waag-secure-boot.rst
- [x] ~~PR #3944 tutorials/acrn-dm_QoS.rst~~
- [x] PR #3944 getting-started/rt_industry.rst
- [x] ~~PR #3944 getting-started/changelog_QuickSetupScript.txt~~
- [x] PR #3847, #3920 developer-guides/hld/hld-security.rst
- [x] PR #3845 developer-guides/hld/hv-hypercall.rst
- [x] PR #3857, #3929, #4006 developer-guides/hld/hv-cpu-virt.rst
- [x] PR #3934, #3961 developer-guides/hld/hld-overview.rst
- [x] PR #3862 developer-guides/hld/hv-memmgt.rst

**Comment by deb-intel** [comment]
I am closing this issue now. Moving forward, I will keep a running list of documents that need to be edited if a backlog arises.
